### ISSUE TITLE
Selbstversorgunghütte

### ISSUE THREAD

**Issue by Herbert-Khrill** [sebader/alpinehutproject#56]
First of all, I love your project ! Thank you very much, it saved me more than once.

Could you ad the Selbstversorgunghütten which are connected to the online reservation system ?
thanks
https://www.alpenverein-muenchen-oberland.de/selbstversorgerhuetten

**Comment by sebader** [comment]
Thanks for opening the issue!
That seems to be some completely different reservation system. I'll take a look how easy it might be to integrate that, but probably not a quick fix as my entire logic so far is targeted towards the common system of the Alpenverein.

**Comment by Herbert-Khrill** [comment]
Thanks ! One question, do you have a lot of traffic on this website?I think the DAV made it very complicated to book a Hut on purpose.Everyone I tell about your tool is amazed. You make people happy for sure



    Le mercredi 1 février 2023 à 22:32:52 UTC+1, Sebastian ***@***.***> a écrit :  
 
 


Thanks for opening the issue!
That seems to be some completely different reservation system. I'll take a look how easy it might be to integrate that, but probably not a quick fix as my entire logic so far is targeted towards the common system of the Alpenverein.

**Comment by sebader** [comment]
I had a look but there is really no easy way to fetch the availability data of that Selbstversorgerhütten page, sorry.

Number of visitors varies, but even in the winter now its a few dozen per week, usually. So yeah, spread the word! Happy for anybody this helps :)

**Comment by Herbert-Khrill** [comment]
That was just an idea, thanks for all !

Le 4 févr. 2023, 20:33, à 20:33, Sebastian ***@***.***> a écrit:
